site_name: ClashRS User Mannual
docs_dir: docs
site_url: https://docs.watfaq.com/clash/
repo_url: https://github.com/Watfaq/clash-rs
edit_uri: https://github.com/Watfaq/docs/blob/master/docs/
repo_name: clash-rs

theme:
  logo: artwork/logo.png
  favicon: artwork/logo.png
  name: material
  features:
    - search.highlight
    - navigation.tracking
    # - navigation.instant
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - content.action.edit
    # markdown_extensions Code blocks
    - content.code.copy
    - content.code.annotate

    # markdown_extensions.pymdownx.tabbed
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Foramtting
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Welcome: index.md
  - Quick start:
    - quick-start/index.md
    - CLI: quick-start/cli.md
    - GUI: quick-start/gui.md
  - Configuration:
    - config/index.md
    - Full Example: config/full.md
    - Inbounds: 
      - config/inbounds/index.md
      - HTTP: config/inbounds/http.md
      - SOCKS: config/inbounds/socks.md
      - Tunnel: config/inbounds/tunnel.md

plugins:
  # - search
  # - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
          site_name: "ClashRS User Mannual"
        - build: true
          default: false
          locale: zh
          name: 简体中文
          site_name: "ClashRS 用户文档"
          nav_translations:
            Welcome: 欢迎
            Quick start: 快速开始
            CLI: 命令行界面
            GUI: 图形用户界面
            Configuration: 配置
            Full Example: 完整示例

extra:
  analytics:
    provider: google
    property: G-YQC14KYW3F
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Watfaq/clash-rs
    - icon: material/file-document
      link: https://github.com/Watfaq/docs
